# Generated by Django 3.2.7 on 2021-10-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemodel',
            name='type',
            field=models.TextField(max_length=10, verbose_name='type of role'),
        ),
    ]
