# Generated by Django 3.2.7 on 2021-10-08 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20211009_0123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamemodel',
            old_name='compet_team02',
            new_name='guest',
        ),
        migrations.RenameField(
            model_name='gamemodel',
            old_name='compet_team01',
            new_name='host',
        ),
    ]
